#!/usr/bin/env bash
#
# Create a stable self-signed code-signing identity for local development, and
# (re-)sign a built app with it.
#
# WHY THIS EXISTS
#
# macOS ties permission grants — Accessibility, "access data from other apps" —
# to an app's *code identity*. With ad-hoc signing (`CODE_SIGN_IDENTITY="-"`)
# that identity is the cdhash of the binary, which changes on every build, so
# every rebuild looks like a brand-new app and macOS asks for permission again.
#
# Signing with a certificate instead makes the identity depend on the
# certificate and the bundle id, both of which are stable — so a grant survives
# rebuilds and automated runs stop stalling on consent prompts.
#
# USAGE
#   scripts/dev-signing-identity.sh create              # once per machine
#   scripts/dev-signing-identity.sh sign <path/to.app>  # after each build
#
# The certificate is self-signed and lives only in your login keychain. It is
# for local development; releases still need a real Developer ID.

set -euo pipefail

IDENTITY_NAME="${EYESONYOU_DEV_IDENTITY:-EyesOnYou Dev}"
KEYCHAIN="${HOME}/Library/Keychains/login.keychain-db"

have_identity() {
    # Deliberately not `-v`: a self-signed certificate reports
    # CSSMERR_TP_NOT_TRUSTED and is filtered out of the "valid" list, yet
    # `codesign` signs with it happily. Trust matters for verifying a signature,
    # not for producing one.
    security find-identity -p codesigning "$KEYCHAIN" 2>/dev/null \
        | grep -qF "$IDENTITY_NAME"
}

create_identity() {
    if have_identity; then
        echo "Identity '$IDENTITY_NAME' already exists."
        write_local_xcconfig
        return 0
    fi

    local workdir
    workdir="$(mktemp -d)"
    trap 'rm -rf "$workdir"' RETURN

    cat >"$workdir/openssl.cnf" <<EOF
[ req ]
distinguished_name = dn
prompt             = no
x509_extensions    = v3

[ dn ]
CN = $IDENTITY_NAME

[ v3 ]
basicConstraints     = critical,CA:false
keyUsage             = critical,digitalSignature
extendedKeyUsage     = critical,codeSigning
EOF

    # macOS `security import` cannot verify the MAC on PKCS#12 bundles written by
    # OpenSSL 3 defaults, so use the system LibreSSL, which stays compatible.
    local ssl=/usr/bin/openssl

    echo "Generating a self-signed code-signing certificate…"
    "$ssl" req -newkey rsa:2048 -nodes \
        -keyout "$workdir/key.pem" \
        -x509 -days 3650 \
        -out "$workdir/cert.pem" \
        -config "$workdir/openssl.cnf" >/dev/null 2>&1

    # `security import` rejects empty-password PKCS#12 bundles (MAC verification
    # failure), so use a throwaway passphrase — the file is deleted on exit.
    local p12_pass="eyesonyou-dev"
    "$ssl" pkcs12 -export \
        -inkey "$workdir/key.pem" \
        -in "$workdir/cert.pem" \
        -out "$workdir/identity.p12" \
        -passout "pass:$p12_pass" >/dev/null 2>&1

    # -T codesign lets codesign use the key without prompting for the keychain
    # password on every signature.
    security import "$workdir/identity.p12" \
        -k "$KEYCHAIN" \
        -P "$p12_pass" \
        -T /usr/bin/codesign >/dev/null

    # Without this, the first signing attempt still shows a keychain dialog.
    security set-key-partition-list -S apple-tool:,apple:,codesign: \
        -s -k "" "$KEYCHAIN" >/dev/null 2>&1 || true

    write_local_xcconfig

    echo "Created '$IDENTITY_NAME'."
    echo
    echo "The certificate is not trusted by the system, which is fine for local"
    echo "signing. To silence Gatekeeper warnings you may mark it 'Always Trust'"
    echo "for Code Signing in Keychain Access."
}

# Xcode builds do not inherit the shell environment, so pointing the build at the
# identity has to happen through a config file the project includes.
write_local_xcconfig() {
    local dir
    dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/config"
    mkdir -p "$dir"
    cat >"$dir/LocalSigning.xcconfig" <<EOF
// Generated by scripts/dev-signing-identity.sh — git-ignored, machine-local.
// Keeps Accessibility and notification grants alive across rebuilds by giving
// every build the same code identity.
EYESONYOU_CODE_SIGN_IDENTITY = $IDENTITY_NAME
EOF
    echo "Wrote $dir/LocalSigning.xcconfig"
}

sign_app() {
    local app="$1"
    if [[ ! -d "$app" ]]; then
        echo "error: '$app' is not an app bundle" >&2
        exit 1
    fi
    if ! have_identity; then
        echo "error: identity '$IDENTITY_NAME' not found — run: $0 create" >&2
        exit 1
    fi

    # --deep so the nested debug dylib Xcode emits is re-signed too; without it
    # the bundle seal no longer matches and the app fails to load.
    codesign --force --deep --sign "$IDENTITY_NAME" \
        --options runtime \
        --timestamp=none \
        "$app"

    echo "Signed $app as '$IDENTITY_NAME'."
    codesign --display --verbose=2 "$app" 2>&1 | sed -n 's/^Authority=/  authority: /p'
}

case "${1:-}" in
    create)
        create_identity
        ;;
    sign)
        sign_app "${2:?usage: $0 sign <path/to.app>}"
        ;;
    *)
        cat >&2 <<EOF
usage:
  $0 create              create the stable dev signing identity (once)
  $0 sign <path/to.app>  re-sign a built app with it (after each build)

env:
  EYESONYOU_DEV_IDENTITY  certificate common name (default: "EyesOnYou Dev")
EOF
        exit 1
        ;;
esac
